#[derive(Copy, Clone, Eq, PartialEq, Debug, serde::Serialize, serde::Deserialize, sqlx::Type)]
#[serde(rename = "card", rename_all = "snake_case")]
#[sqlx(rename = "enum_card", rename_all = "snake_case")]
pub enum CardId {
    Ambush,
    BirdyBindle,
    Armorers,
    WoodlandRunners,
    ArmsTrader,
    Crossbow,
    Sappers,
    BrutalTactics,
    RoyalClaim,
    GentlyUsedKnapsack,
    RootTea,
    TravelGear,
    ProtectionRacket,
    FoxfolkSteel,
    Anvil,
    StandAndDeliver,
    TaxCollector,
    FavorOfTheFoxes,
    SmugglersTrail,
    AVisitToFriends,
    BakeSale,
    CommandWarren,
    BetterBurrowBank,
    Cobbler,
    FavorOfTheRabbits,
    MouseInASack,
    Investments,
    Sword,
    ScoutingParty,
    Codebreakers,
    FavorOfTheMice,
    Dominance,
    Spy,
}
